package jlite.lexer;
public enum TokenType {
    SELECT,FROM,WHERE,INSERT,INTO,VALUES,UPDATE,SET,DELETE,CREATE,DROP,ALTER,TABLE,INDEX,ON,
    JOIN,INNER,LEFT,RIGHT,OUTER,CROSS,GROUP,BY,HAVING,ORDER,ASC,DESC,LIMIT,OFFSET,
    DISTINCT,AS,AND,OR,NOT,IN,BETWEEN,LIKE,IS,NULL,BEGIN,COMMIT,ROLLBACK,SAVEPOINT,
    PRIMARY,KEY,FOREIGN,REFERENCES,UNIQUE,DEFAULT,CHECK,ADD,COLUMN,RENAME,
    INT,BIGINT,FLOAT,DOUBLE,TEXT,VARCHAR,BOOLEAN,DATE,TIMESTAMP,
    INTEGER_LITERAL,FLOAT_LITERAL,STRING_LITERAL,BOOLEAN_LITERAL,NULL_LITERAL,
    IDENTIFIER,EQ,NEQ,LT,GT,LTE,GTE,PLUS,MINUS,STAR,SLASH,PERCENT,
    LPAREN,RPAREN,COMMA,SEMICOLON,DOT,EOF
}
